spring:
  cloud:
    stream:
      function:
        definition : paymentProcessor
      bindings:
        paymentProcessor-in-0 :
          destination: order-event
        paymentProcessor-out-0:
          destination: payment-event


#spring:
#  application:
#    name: PAYSLIP-SERVICE
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost

#logging:
#  file: D:/elk_logs/microservice.log