spring:
  cloud:
    stream:
      function:
        definition : walletCreateProcessor;walletEventConsumer
      bindings:
        walletEventConsumer-in-0:
          destination: user-event
        walletCreateProcessor-out-0:
          destination: wallet-event

#spring:
#  application:
#    name: EMPLOYEE-SERVICE
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost

#logging:
#  file: D:/elk_logs/microservice.log