spring:
  cloud:
    stream:
      function:
        definition : orderSupplier;paymentEventConsumer
      bindings:
        orderSupplier-out-0:
          destination: order-event
        paymentEventConsumer-in-0 :
          destination: payment-event


#spring:
#  application:
#    name: TAX-SERVICE
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost

#logging:
#  file: D:\elk_logs